name:                xmonad-config
version:             0.1.0.0
github:              "vonabarak/xmonad-config"
license:             BSD3
author:              "vonabarak"
maintainer:          "github@vonabarak.ru"
copyright:           "2022 vonabarak"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vonabarak/xmonad-config#readme>

dependencies:
- base >= 4.7 && < 5


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - xmonad
  - xmonad-contrib
  - xmonad-extras
  - containers
  - hint
  - process
  - X11
  - unix
  - filepath
  - extra
  - directory
  - cryptonite
  - utf8-string
  - uuid
  - time

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config
  xmonadctl:
    main:                xmonadctl.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - X11
  xmobar:
    main:                xmobar.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmobar
  runner:
    main:                runner.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad-config
